version: '3'

services:

  activity-server:
    build:
      context: ./../activity-server
      dockerfile: ./../activity-server/activity-server.dockerfile
    restart: always
    ports:
      - "9090:9090"
    deploy:
      mode: replicated
      replicas: 1

  service-server:
    build:
      context: ./../ServiceServer
      dockerfile: ./../ServiceServer/service-server.dockerfile
    restart: always
    ports:
      - "8090:8090"
    deploy:
      mode: replicated
      replicas: 1
